% Diccionario ESP - ENG

% Determinantes
determinante(esp, det(X)) --> [X], {det(X,_)}.
determinante(eng, det(X)) --> [Y], {det(X,Y)}.
det(el,the).
det(la,the).
det(las,the).
det(un, a).
det(una, a).
det(mi, my).
det(la, the).
det(este, this).
det(los, the).
det(aquella, that).
det(las, the).
det(un, a).
det(esas, those).
det(una, a).
det(su, his).
det(sus, their).
det(este, this).
det(nuestro, our).
det(solo, just).
det(esta, this).
det(nuestra, our).
det(donde, where).
det(tu, your).
det(ese, that).
det(otro, another).
det(unas, some).
det(esa, that).
det(eso, that).
det(mis, my).
det(algunas, some).
det(menos, less).
det(esos, those).
det(alguna, some).
det(estos, these).
det(unos, some).
det(aquel, that).
det(esto, this).
det(aquellos, that).
det(otras, other).
det(nuestros, our).
det(algunos, some).
det(algun, any).
det(estas, these).
det(muchas, a-lot-of).

% Sustantivos
nombre(esp, n(X)) --> [X], {n(X,_)}.
nombre(eng, n(X)) --> [Y], {n(X,Y)}.
n(hombre, man).
n(mujer, woman).
n(manzana, apple).
n(manzanas, apples).
n(gato, cat).
n(raton, mouse).
n(alumno, student).
n(universidad, university).
n(juan, john).
n(maria, mary).
n(jose, joseph).
n(hector, hector).
n(irene, irene).
n(filosofia, philosophy).
n(derecho, law).
n(cafe, coffee).
n(mesa, table).
n(periodico, newspaper).
n(patatas, potatoes).
n(cerveza, beer).
n(paella, paella).
n(novela, novel).
n(zumo, juice).
n(procesador, processor).
n(textos, texts).
n(herramienta, tool).
n(documentos, documents).
n(vecino, neighbor).
n(escribir, writing).
n(rocodromo, climbing-wall).
n(tardes, afternoon).
n(veces, times).
n(embargo, nevertheless).
n(partido, match).
n(pesetas, coins).
n(personas, people).
n(orden, order).
n(grupo, group).
n(cuenta, account).
n(misma, same).
n(programa, program).
n(palabras, words).
n(segunda, second).
n(empresa, business).
n(puesto, position).
n(cosas, things).
n(ciudad, city).
n(lo, it).
n(libro, book).
n(manera, manner).
n(politico, politician).
n(persona, person).
n(sistema, system).
n(ellas, they).
n(le, him).
n(historia, history).
n(total, total).
n(me, i).
n(juan, john).
n(tipo, type).
n(dios, god).
n(cuatro, four).
n(condiciones, conditions).
n(punto, point).
n(mejico, mexico).
n(fuerza, force).
n(ello, it).
n(todo, everything).
n(noche, night).
n(accion, action).
n(ser, being).
n(amor, love).
n(agua, water).
n(policia, police).
n(dos, two).
n(puerta, door).
n(haber, there-is).
n(pesar, to-weight).
n(situacion, situation).
n(zona, zone).
n(calle, street).
n(anos, years).
n(ejemplo, example).
n(musica, music).
n(acuerdo, agreement).
n(vista, view).
n(usted, you).
n(campo, field).
n(estados, states).
n(que, what).
n(nadie, nobody).
n(saber, knowledge).
n(paises, countries).
n(obras, works).
n(yo, i).
n(horas, hours).
n(razon, reason).
n(ex, ex).
n(vez, time).
n(tarde, late).
n(ninos, kids).
n(ley, law).
n(presencia, presence).
n(todos, everyone).
n(tema, topic).
n(guerra, war).
n(dinero, money).
n(nos, we).
n(desarrollo, development).
n(comision, commission).
n(proceso, process).
n(antonio, anthony).
n(parte, part).
n(realidad, reality).
n(servicio, service).
n(sentido, way).
n(hijo, son).
n(lado, side).
n(ultima, last).
n(uno, one).
n(ciento, hundread).
n(cambio, change).
n(hablar, speaking).
n(tiempo, time).
n(mismo, same).
n(mano, hand).
n(minutos, minutes).
n(produccion, production).
n(estar, to-be).
n(camino, path).
n(san, saint).
n(seis, six).
n(numero, number).
n(quien, whom).
n(vida, life).
n(sociedad, society).
n(fondo, background).
n(direccion, direction).
n(centro, center).
n(papel, paper).
n(te, tea).
n(padre, father).
n(otros, other).
n(gente, people).
n(barcelona, barcelona).
n(final, final).
n(idea, idea).
n(relacion, relationship).
n(cuerpo, body).
n(obra, work).
n(dado, dice).
n(otra, another).
n(base, base).
n(gobierno, government).
n(capital, capital).
n(ultimo, last).
n(ambos, both).
n(madre, mother).
n(europa, europe).
n(libertad, freedom).
n(dia, day).
n(modo, mode).
n(relaciones, relationships).
n(problema, problem).
n(espacio, space).
n(ella, she).
n(cinco, five).
n(medios, media).
n(tres, three).
n(carlos, charles).
n(ir, going).
n(hombres, men).
n(informacion, information).
n(poblacion, population).
n(ojos, eyes).
n(empresas, businesses).
n(muerte, death).
n(estudio, study).
n(pais, country).
n(nombre, name).
n(salud, health).
n(servicios, services).
n(haya, beech).
n(ano, year).
n(mujeres, women).
n(principio, principle).
n(siglo, century).
n(estado, state).
n(cultura, culture).
n(meses, months).
n(manana, tomorrow).
n(forma, shape).
n(media, half).
n(caso, case).
n(nosotros, we).
n(nada, nothing).
n(hora, hour).
n(primeros, firsts).
n(hacer, doing).
n(arte, art).
n(general, general).
n(pueblo, town).
n(paz, peace).
n(sector, sector).
n(dar, giving).
n(imagen, image).
n(problema, problem).
n(medida, measure).
n(presidente, president).
n(don, mr).
n(mayor, elder).
n(datos, data).
n(tu, you).
n(consejo, advice).
n(les, they).
n(verdad, truth).
n(interes, interest).
n(algo, something).
n(julio, july).
n(grupos, groups).
n(casa, house).
n(miembros, members).
n(ellos, they).
n(ninguna, none).
n(cabeza, head).
n(cara, face).
n(primera, first).
n(edad, age).
n(luis, louise).
n(movimiento, movement).
n(tierra, ground).
n(equipo, team).
n(momento, moment).
n(segundo, second).
n(puntos, points).
n(millones, millions).
n(director, director).
n(actividad, activity).
n(espana, spain).
n(uso, using).
n(casos, cases).
n(nino, kid).
n(manos, hands).
n(nivel, level).
n(hoy, today).
n(futuro, future).
n(lugar, place).
n(familia, family).
n(madrid, madrid).
n(mes, month).
n(partir, split).
n(trabajo, work).
n(falta, lack).
n(llegar, arriving).
n(ministro, minister).
n(decir, saying).
n(cosa, thing).
n(primero, first).
n(posibilidad, posibility).
n(seguridad, security).
n(dias, days).
n(resultados, results).
n(educacion, education).
n(politica, politics).
n(atencion, atention).
n(gonzalez, gonzalez).
n(respecto, regard).
n(capacidad, capacity).
n(semana, week).
n(efecto, efect).
n(varios, several).
n(real, real).
n(valor, value).
n(pasado, past).
n(aire, air).
n(primer, first).
n(voz, voice).
n(investigacion, investigation).
n(medio, half).
n(paso, step).
n(siguiente, next).
n(senor, sir).
n(figura, figure).
n(mil, thousand).
n(central, central).
n(comunidad, comunity).
n(proyecto, proyect).
n(necesidad, need).
n(mercado, market).
n(serie, series).
n(poder, power).
n(mayoria, mayority).
n(organizacion, organization).
n(luz, light).
n(calidad, quality).
n(frente, forehead).
n(fin, end).
n(propia, own).
n(tener, owning).
n(sobre, envelope).

% Verbos
verbo(esp, v(X)) --> [X], {v(X,_)}.
verbo(eng, v(X)) --> [Y], {v(X,Y)}.
v(ama, love).
v(come, eats).
v(estudia, studies).
v(bebe, drinks).
v(es, is).
v(toma, takes).
v(recoge, collect).
v(lee, reeds).
v(comen, eat).
v(beben, drink).
v(prefiere, prefers).
v(canta, sings).
v(salta, jumps).
v(escala, climbs).
v(sirve, serves).
v(cazo, hunted).
v(vimos, saw).
v(era, was).
v(ver, see).
v(iba, was-going).
v(pueden, can).
v(quiere, want).
v(tienen, have).
v(fueron, went).
v(van, go).
v(he, have).
v(como, eat).
v(sera, will-be).
v(ha, has).
v(creo, think).
v(tengo, have).
v(dice, says).
v(son, are).
v(parece, looks).
v(fue, was).
v(habia, there-was).
v(sabe, knows).
v(era, was).
v(esta, was).
v(habian, there-were).
v(hizo, did).
v(hubiera, had).
v(han, had).
v(hay, there-is).
v(puede, can).
v(tiene, have).
v(estoy, am).
v(dio, gave).
v(eran, were).
v(hace, its).
v(dijo, said).
v(sido, been).
v(siendo, being).
v(estaba, was).
v(deben, must).
v(da, give).
v(podria, could).
v(seria, would-be).
v(existe, exists).
v(hecho, done).
v(llego, arrive).
v(estan, are).
v(podia, could).
v(soy, am).
v(hacia, did).
v(estaban, were).
v(sigue, go-on).
v(hemos, have).
v(debe, must).
v(trata, treats).
v(tuvo, had).
v(se, know).
v(va, goes).
v(sea, be).
v(tenia, had).

% Adjetivos
adjetivo(esp, adj(X)) --> [X], {adj(X,_)}.
adjetivo(eng, adj(X)) --> [Y], {adj(X,Y)}.
adj(roja, red).
adj(rojas, red).
adj(negro, black).
adj(grande, big).
adj(gris, gray).
adj(pequeno, little).
adj(alta, tall).
adj(moreno, brown).
adj(fritas, fried).
adj(potente, powerful).
adj(lento, slow).
adj(agil, agile).
adj(delicado, delicate).
adj(espanol, spanish).
adj(buena, good).
adj(nueva, new).
adj(internacional, international).
adj(propia, owned).
adj(social, social).
adj(igual, equal).
adj(ultimos, last).
adj(espanola, spanish).
adj(unico, unique).
adj(bajo, low).
adj(grandes, big).
adj(buen, good).
adj(posible, possible).
adj(importante, important).
adj(bien, good).
adj(especial, special).
adj(diferentes, differents).
adj(actual, actual).
adj(gran, big).
adj(publico, public).
adj(alto, tall).
adj(personal, personal).
adj(unidos, joined).
adj(visto, seen).
adj(dicho, said).
adj(bueno, good).
adj(cierto, true).
adj(dificil, difficult).
adj(joven, young).
adj(largo, long).
adj(nacional, national).
adj(pronto, soon).
adj(nuevos, new).
adj(nuevo, new).
adj(cerca, near).
adj(mal, bad).
adj(necesario, necessary).
adj(nuevas, new).

% Conjunciones
conjuncion(esp, conj(X)) --> [X], {conj(X,_)}.
conjuncion(eng, conj(X)) --> [Y], {conj(X,Y)}.
conj(y, and).
conj(e, and).
conj(ni, neither).
conj(pero, but).
conj(aunque, although).
conj(o, or).
conj(sino, but).
conj(mientras, while).

% Adverbios
adverbio(esp, adv(X)) --> [X], {adv(X,_)}.
adverbio(eng, adv(X)) --> [Y], {adv(X,Y)}.
adv(cuando, when).
adv(que, that).
adv(donde, where).
adv(mientras, while).
adv(muy, very).
adv(bastante, quite).
adv(ayer, yesterday).
adv(solamente, only).
adv(cual, which).
adv(no, no).
adv(ahi, there).
adv(fin, end).
adv(mas, more).
adv(muchos, more).
adv(si, yes).
adv(dentro, inside).
adv(ya, already).
adv(cuando, when).
adv(cualquier, any).
adv(aun, still).
adv(tambien, also).
adv(fuera, outside).
adv(muy, very).
adv(interior, inside).
adv(tampoco, also).
adv(ningun, none).
adv(porque, because).
adv(solo, only).
adv(asi, so).
adv(alli, over-there).
adv(ahora, now).
adv(cada, each).
adv(despues, then).
adv(demas, rest).
adv(incluso, also).
adv(traves, through).
adv(tan, so).
adv(durante, during).
adv(siempre, always).
adv(tanto, so-much).
adv(si, if).
adv(antes, before).
adv(todavia, still).
adv(anterior, previous).
adv(poco, bit).
adv(ayer, yesterday).
adv(junto, together).
adv(mucho, a-lot).
adv(etc, etc).
adv(cuanto, how-much).
adv(ademas, besides).
adv(quien, who).
adv(pues, then).
adv(mejor, better).
adv(propio, own).
adv(entonces, so).
adv(todas, all).
adv(como, how).
adv(casi, almost).
adv(toda, all).
adv(tal, such).
adv(luego, then).
adv(aqui, here).
adv(quienes, who).
adv(nunca, never).

% Preposiciones
preposicion(esp, prep(X)) --> [X], {prep(X,_)}.
preposicion(eng, prep(X)) --> [Y], {prep(X,Y)}.
prep(a, to).
prep(de, of).
prep(para, to).
prep(en, in).
prep(por, by).
prep(con, with).
prep(tras, after).
prep(al, to-the).
prep(sin, without).
prep(sobre, about).
prep(entre, between).
prep(hasta, until).
prep(desde, from).
prep(segun, according-to).
prep(contra, against).
prep(mediante, through).
prep(ante, before).
prep(hacia, to).